[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
pytest = "*"
pytest-mock = "*"
pipenv = "*"

[packages]
flask = "==0.12.1"
pprint = "*"
regex = "*"
six = "*"
requests = {git = "https://github.com/requests/requests.git", editable = true}

[requires]
python_version = "3.8"