---
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  sam-app
  Sample SAM Template for sam-app
Metadata:
  AWS::ServerlessRepo::Application:
    Name: sam-app
    Description: Lambda aliasing and versioning example
    Author: kthblmfld
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['appId:123']
    HomePageUrl: https://github.com/kthblmfld/sam-app
    SemanticVersion: 0.0.4
    SourceCodeUrl: https://github.com/kthblmfld/sam-app
Globals:
  Function:
    Timeout: 3
Mappings:
  SayHelloFeature:
    devint:
      status: true
    qa:
      status: true
    prod:
      status: false
    sandbox:
      status: true
    stage:
      status: true
Parameters:
  deploymentEnvironment:
    AllowedValues:
    - sandbox
    - devint
    - qa
    - stage
    - prod
    Default: sandbox
    Type: String
Resources:
  HelloWorldFunction:
    Properties:
      AutoPublishAlias: !Ref deploymentEnvironment
      CodeUri: hello_world_function
      DeploymentPreference:
#        Canary deployment options eg: Canary10Percent5Minutes, Linear10PercentEvery1Minute...
#        https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html
        Type: AllAtOnce

#          Type: Canary10Percent10Minutes
#          Alarms:
#            # A list of alarms that you want to monitor
#            - !Ref AliasErrorMetricGreaterThanZeroAlarm
#            - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
#          Hooks:
#            # Validation Lambda functions that are run before & after traffic shifting
#            PreTraffic: !Ref PreTrafficLambdaFunction
#            PostTraffic: !Ref PostTrafficLambdaFunction

      Environment:
        Variables:
          DeployedEnv: !Ref deploymentEnvironment
          SayHelloFeature1: !FindInMap [SayHelloFeature, !Ref deploymentEnvironment, status]
      Events:
        HelloWorld:
          Properties:
            Pattern:
              detail-type:
              - "EC2 Instance State-change Notification"
              source:
              - aws.ec2
          Type: CloudWatchEvent
      Handler: hello_world/app.lambda_handler
      Runtime: python3.8
    Type: "AWS::Serverless::Function"
Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: HelloWorldFunctionRole.Arn
Transform: "AWS::Serverless-2016-10-31"
