---
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  sam-app
  Sample SAM Template for sam-app
Globals:
  Function:
    Timeout: 3
Mappings:
  SayHelloFeature:
    devint:
      status: true
    prod:
      status: false
    sandbox:
      status: true
    stage:
      status: true
Parameters:
  deploymentEnvironment:
    AllowedValues:
    - sandbox
    - devint
    - stage
    - prod
    Default: sandbox
    Type: String
Resources:
  HelloWorldFunction:
    Properties:
      AutoPublishAlias: deploymentEnvironment
      CodeUri: hello_world_function
      DeploymentPreference:
        Type: Linear10PercentEvery10Minutes
      Environment:
        Variables:
          DeployedEnv: !Ref deploymentEnvironment
          SayHelloFeature1: !FindInMap [SayHelloFeature, !Ref deploymentEnvironment, status]
      Events:
        HelloWorld:
          Properties:
            Pattern:
              detail-type:
              - "EC2 Instance State-change Notification"
              source:
              - aws.ec2
          Type: CloudWatchEvent
      Handler: hello_world/app.lambda_handler
      Runtime: python3.8
    Type: "AWS::Serverless::Function"
Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: HelloWorldFunctionRole.Arn
Transform: "AWS::Serverless-2016-10-31"
